server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: ${APPLICATION_NAME:star-wars-planets}
  datasource:
    url: jdbc:h2:mem:wwc2023
    username: wwc2023
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
#  jpa:
#    database: postgresql
#    show-sql: ${HIBERNATE_SHOW_SQL:true}
#    hibernate:
#      ddl-auto: update # spring criando as tabelas automaticamente
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    open-in-view: false
#  datasource:
#    platform: postgres
#    driverClassName: org.postgresql.Driver
#    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/star-wars-planets}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:20}
#      minimum-idle: ${HIKARI_MINIMUM_IDLE:2}
