version: '3'
services:
  postgres:
    networks:
      - net
    container_name: star-wars-planets_db
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: star-wars-planets
networks:
  net:
    driver: bridge
